# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fd9609b10dc9c8adbbec3f96a9e34075522a0b6aa613cbbd208a0dcdd9d8ba35c6e2913777202ce4e5623409209278937ad19c8127c834dbb8220cd4e8fa869

test:
  secret_key_base: 79e2fad6032ab4dfc172ea50dfc20171f0f1dac495ea88a1c20bda7392363ca85d9936661d250313f948b584574ae630142f3500b219140d6c5408df220d963f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
